#!/bin/bash
# copy the adhost to /usr/local/bin at the first time
echo -e "\e[1m Install update-hosts , and update hosts.安装update-hosts并更新hosts。\e[0m"
sudo -S cp ./update-hosts /usr/local/bin/
sudo -S sed -i '/adhost/d' /usr/local/bin/update-hosts
# hosts src
url_list=(
  "https://raw.githubusercontent.com/googlehosts/hosts/master/hosts-files/hosts"
  "https://adaway.org/hosts.txt"
  "https://raw.githubusercontent.com/vokins/yhosts/master/hosts"
  "https://raw.githubusercontent.com/ds19991999/shell.sh/shell/custom_host"
)

# downloading hosts
for((i=0;i<${#url_list[*]};++i))
do
  url="${url_list[i]}"
  echo "Download hosts from " $url
  curl -#C - -o /tmp/"$i" "$url"
done

echo -e "\e[1;31m Updating hosts need permission to write /etc/hosts. 更新hosts需要有向/etc/hosts写入的权限 \e[0m"
# remove same content
sudo -S sed -i '/localhost/d' /tmp/1 /tmp/2
sudo -S sed -i '/ip6-localhost/d' /tmp/2

# merge hosts
sudo -S cat /tmp/0 /tmp/1 /tmp/2 /tmp/3 >> /tmp/hosts

# copy /tmp/hosts to /etc/hosts
sudo -S cp /tmp/hosts /etc/hosts

echo -e "OK!Some ads will be blocked!更新成功！你可以科学上网。可能需要使用https访问，例如\e[1;35m https://www.google.com/ \e[0m访问Google。"
echo -e "Next time , execute this command \e[1mupdate-hosts\e[0m for updating.下次执行update-hosts这条命令进行更新。"
echo -e "也可以直接加入定时任务：比喻每天 13:30 执行"
echo -e "crontab -e"
echo -e "30 13 * * * sh /usr/local/bin/update-hosts"
