#!/bin/bash
REPO=https://github.com/ds-ebooks/ds-ebooks.github.io.git
git init
git add .
git commit -m "auto commit"
git remote add origin $REPO
git branch gh-pages
git chekout gh-pages
git push -u origin gh-pages -f
